name: github pages

on:
  push:
    branches:
      - ci-test

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - name: Cachix
        uses: cachix/cachix-action@v8
      - uses: cachix/install-nix-action@v11
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210126_f15f0b8/install
          # Configure Nix to enable flakes
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result