name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: cachix
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210126_f15f0b8/install
          # Configure Nix to enable flakes
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Cachix
        uses: cachix/cachix-action@v8
        with:
          name: cryptic
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result
      #  nix build produces a symlink to the result in nix-store
      #  but web3.storage action expects this to not be a symlink. Since it runs in a separate docker container.
      #  Not sure if it's possible to mount the nix path as a volume in the docker container.
      - run: mkdir result-for-web3
      - run: cp -r result/* result-for-web3
      - name: Push to web3.storage
        uses: web3-storage/add-to-web3@v1
        id: web3
        with:
          web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
          path_to_add: ./result-for-web3
